//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Movies = newMoviesTable("KinoTicketSystem", "movies", "")

type moviesTable struct {
	mysql.Table

	// Columns
	ID          mysql.ColumnString
	Title       mysql.ColumnString
	Description mysql.ColumnString
	ReleaseDate mysql.ColumnDate
	TimeInMin   mysql.ColumnInteger
	Fsk         mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MoviesTable struct {
	moviesTable

	NEW moviesTable
}

// AS creates new MoviesTable with assigned alias
func (a MoviesTable) AS(alias string) *MoviesTable {
	return newMoviesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MoviesTable with assigned schema name
func (a MoviesTable) FromSchema(schemaName string) *MoviesTable {
	return newMoviesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MoviesTable with assigned table prefix
func (a MoviesTable) WithPrefix(prefix string) *MoviesTable {
	return newMoviesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MoviesTable with assigned table suffix
func (a MoviesTable) WithSuffix(suffix string) *MoviesTable {
	return newMoviesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMoviesTable(schemaName, tableName, alias string) *MoviesTable {
	return &MoviesTable{
		moviesTable: newMoviesTableImpl(schemaName, tableName, alias),
		NEW:         newMoviesTableImpl("", "new", ""),
	}
}

func newMoviesTableImpl(schemaName, tableName, alias string) moviesTable {
	var (
		IDColumn          = mysql.StringColumn("id")
		TitleColumn       = mysql.StringColumn("title")
		DescriptionColumn = mysql.StringColumn("description")
		ReleaseDateColumn = mysql.DateColumn("release_date")
		TimeInMinColumn   = mysql.IntegerColumn("time_in_min")
		FskColumn         = mysql.IntegerColumn("fsk")
		allColumns        = mysql.ColumnList{IDColumn, TitleColumn, DescriptionColumn, ReleaseDateColumn, TimeInMinColumn, FskColumn}
		mutableColumns    = mysql.ColumnList{TitleColumn, DescriptionColumn, ReleaseDateColumn, TimeInMinColumn, FskColumn}
	)

	return moviesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,
		ReleaseDate: ReleaseDateColumn,
		TimeInMin:   TimeInMinColumn,
		Fsk:         FskColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
