//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ActorPictures struct {
	ID      []byte `sql:"primary_key"`
	ActorID []byte
	PicURL  *string
}
