//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Addressees struct {
	ID       []byte `sql:"primary_key"`
	Street   string
	StreetNr string
	Zipcode  string
	City     string
	Country  string
}
