//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type EventSeats struct {
	ID           []byte `sql:"primary_key"`
	Booked       bool
	BlockedUntil *time.Time
	UserID       []byte
	SeatID       []byte
	EventID      []byte
}
