//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EventMovies struct {
	EventID []byte `sql:"primary_key"`
	MovieID []byte `sql:"primary_key"`
}
