//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EventSeatCategories struct {
	EventID        []byte `sql:"primary_key"`
	SeatCategoryID []byte `sql:"primary_key"`
	Price          int32
}
