//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MovieProducers struct {
	MovieID    []byte `sql:"primary_key"`
	ProducerID []byte `sql:"primary_key"`
}
