//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Orders struct {
	ID              []byte `sql:"primary_key"`
	Totalprice      int32
	IsPaid          bool
	PaymentMethodID []byte
	UserID          []byte
}
