//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Orders struct {
	ID              *uuid.UUID `sql:"primary_key"`
	Totalprice      int32
	IsPaid          bool
	PaymentMethodID *uuid.UUID
	UserID          *uuid.UUID
}
