//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Producers struct {
	ID          []byte `sql:"primary_key"`
	Name        string
	Age         int32
	Description string
}
