//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Reviews struct {
	ID        uuid.UUID `sql:"primary_key"`
	Rating    int32
	Comment   string
	Datetime  time.Time
	IsSpoiler *bool
	UserID    uuid.UUID
	MovieID   uuid.UUID
}
