//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SeatCategories struct {
	ID           []byte `sql:"primary_key"`
	CategoryName string
}
