//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Tickets struct {
	ID              []byte `sql:"primary_key"`
	Validated       bool
	Price           int32
	PriceCategoryID []byte
	OrderID         []byte
	EventSeatID     []byte
}
