// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/controllers/movie_controller.go
//
// Generated by this command:
//
//	mockgen -source=./src/controllers/movie_controller.go -destination=./src/mocks/movie_controller_mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/ELITE-Kinoticketsystem/Backend-KTS/src/gen/KinoTicketSystem/model"
	models "github.com/ELITE-Kinoticketsystem/Backend-KTS/src/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMovieControllerI is a mock of MovieControllerI interface.
type MockMovieControllerI struct {
	ctrl     *gomock.Controller
	recorder *MockMovieControllerIMockRecorder
}

// MockMovieControllerIMockRecorder is the mock recorder for MockMovieControllerI.
type MockMovieControllerIMockRecorder struct {
	mock *MockMovieControllerI
}

// NewMockMovieControllerI creates a new mock instance.
func NewMockMovieControllerI(ctrl *gomock.Controller) *MockMovieControllerI {
	mock := &MockMovieControllerI{ctrl: ctrl}
	mock.recorder = &MockMovieControllerIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieControllerI) EXPECT() *MockMovieControllerIMockRecorder {
	return m.recorder
}

// CreateMovie mocks base method.
func (m *MockMovieControllerI) CreateMovie(movie *models.MovieDTOCreate) (*uuid.UUID, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMovie", movie)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// CreateMovie indicates an expected call of CreateMovie.
func (mr *MockMovieControllerIMockRecorder) CreateMovie(movie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMovie", reflect.TypeOf((*MockMovieControllerI)(nil).CreateMovie), movie)
}

// DeleteMovie mocks base method.
func (m *MockMovieControllerI) DeleteMovie(movieId *uuid.UUID) *models.KTSError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMovie", movieId)
	ret0, _ := ret[0].(*models.KTSError)
	return ret0
}

// DeleteMovie indicates an expected call of DeleteMovie.
func (mr *MockMovieControllerIMockRecorder) DeleteMovie(movieId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMovie", reflect.TypeOf((*MockMovieControllerI)(nil).DeleteMovie), movieId)
}

// GetMovieById mocks base method.
func (m *MockMovieControllerI) GetMovieById(movieId *uuid.UUID) (*models.MovieWithEverything, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieById", movieId)
	ret0, _ := ret[0].(*models.MovieWithEverything)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// GetMovieById indicates an expected call of GetMovieById.
func (mr *MockMovieControllerIMockRecorder) GetMovieById(movieId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieById", reflect.TypeOf((*MockMovieControllerI)(nil).GetMovieById), movieId)
}

// GetMovieByName mocks base method.
func (m *MockMovieControllerI) GetMovieByName(name *string) (*model.Movies, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieByName", name)
	ret0, _ := ret[0].(*model.Movies)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// GetMovieByName indicates an expected call of GetMovieByName.
func (mr *MockMovieControllerIMockRecorder) GetMovieByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieByName", reflect.TypeOf((*MockMovieControllerI)(nil).GetMovieByName), name)
}

// GetMovies mocks base method.
func (m *MockMovieControllerI) GetMovies() (*[]model.Movies, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovies")
	ret0, _ := ret[0].(*[]model.Movies)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// GetMovies indicates an expected call of GetMovies.
func (mr *MockMovieControllerIMockRecorder) GetMovies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovies", reflect.TypeOf((*MockMovieControllerI)(nil).GetMovies))
}

// GetMoviesWithGenres mocks base method.
func (m *MockMovieControllerI) GetMoviesWithGenres() (*[]models.MovieWithGenres, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviesWithGenres")
	ret0, _ := ret[0].(*[]models.MovieWithGenres)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// GetMoviesWithGenres indicates an expected call of GetMoviesWithGenres.
func (mr *MockMovieControllerIMockRecorder) GetMoviesWithGenres() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesWithGenres", reflect.TypeOf((*MockMovieControllerI)(nil).GetMoviesWithGenres))
}

// UpdateMovie mocks base method.
func (m *MockMovieControllerI) UpdateMovie(movie *model.Movies) *models.KTSError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMovie", movie)
	ret0, _ := ret[0].(*models.KTSError)
	return ret0
}

// UpdateMovie indicates an expected call of UpdateMovie.
func (mr *MockMovieControllerIMockRecorder) UpdateMovie(movie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMovie", reflect.TypeOf((*MockMovieControllerI)(nil).UpdateMovie), movie)
}
