// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/controllers/user_controller.go
//
// Generated by this command:
//
//	mockgen -source=./src/controllers/user_controller.go -destination=./src/mocks/user_controller_mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/ELITE-Kinoticketsystem/Backend-KTS/src/gen/KinoTicketSystem/model"
	models "github.com/ELITE-Kinoticketsystem/Backend-KTS/src/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserControllerI is a mock of UserControllerI interface.
type MockUserControllerI struct {
	ctrl     *gomock.Controller
	recorder *MockUserControllerIMockRecorder
}

// MockUserControllerIMockRecorder is the mock recorder for MockUserControllerI.
type MockUserControllerIMockRecorder struct {
	mock *MockUserControllerI
}

// NewMockUserControllerI creates a new mock instance.
func NewMockUserControllerI(ctrl *gomock.Controller) *MockUserControllerI {
	mock := &MockUserControllerI{ctrl: ctrl}
	mock.recorder = &MockUserControllerIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserControllerI) EXPECT() *MockUserControllerIMockRecorder {
	return m.recorder
}

// CheckEmail mocks base method.
func (m *MockUserControllerI) CheckEmail(email string) *models.KTSError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmail", email)
	ret0, _ := ret[0].(*models.KTSError)
	return ret0
}

// CheckEmail indicates an expected call of CheckEmail.
func (mr *MockUserControllerIMockRecorder) CheckEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmail", reflect.TypeOf((*MockUserControllerI)(nil).CheckEmail), email)
}

// CheckUsername mocks base method.
func (m *MockUserControllerI) CheckUsername(username string) *models.KTSError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsername", username)
	ret0, _ := ret[0].(*models.KTSError)
	return ret0
}

// CheckUsername indicates an expected call of CheckUsername.
func (mr *MockUserControllerIMockRecorder) CheckUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsername", reflect.TypeOf((*MockUserControllerI)(nil).CheckUsername), username)
}

// GetUserById mocks base method.
func (m *MockUserControllerI) GetUserById(userId *uuid.UUID) (*model.Users, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", userId)
	ret0, _ := ret[0].(*model.Users)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockUserControllerIMockRecorder) GetUserById(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUserControllerI)(nil).GetUserById), userId)
}

// LoginUser mocks base method.
func (m *MockUserControllerI) LoginUser(loginData models.LoginRequest) (*models.LoginResponse, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", loginData)
	ret0, _ := ret[0].(*models.LoginResponse)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUserControllerIMockRecorder) LoginUser(loginData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUserControllerI)(nil).LoginUser), loginData)
}

// RegisterUser mocks base method.
func (m *MockUserControllerI) RegisterUser(registrationData models.RegistrationRequest) (*models.LoginResponse, *models.KTSError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", registrationData)
	ret0, _ := ret[0].(*models.LoginResponse)
	ret1, _ := ret[1].(*models.KTSError)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserControllerIMockRecorder) RegisterUser(registrationData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserControllerI)(nil).RegisterUser), registrationData)
}
